# application.yml 
--- 
spring: 
  application: 
    name: sentence
eureka: 
  client: 
    serviceUrl: 
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka:8761/eureka/
# leave eureka.instance.leaseRenewalIntervalInSeconds unchanged in production
# just here to provide quicker updates to Eureka for demos
  instance: 
    leaseRenewalIntervalInSeconds: 10
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
server: 
#  port: ${PORT:${SERVER_PORT:0}}
  port: 8080
